development:
  adapter: postgresql
  database: dvine_development
  host: localhost
  username: david
  password: 

test:
  adapter: postgresql
  database: dvine_test
  host: localhost
  username: david
  password: 